# -*- coding: utf-8 -*-
"""ETL Tasks 22BTRCL063 Harshit Kumar Shrivastava.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEOlXskVGDUnp5Or48u1SZphg8TqW-7w
"""

import pandas as pd

df = pd.read_csv('data.csv')

print(df.to_string())

# Rename the variable to something else, such as 'my_append'
my_append = df.head()

df.fillna(0)





import pandas as pd
df = pd.read_csv('data.csv')

df.rename(columns={'Maxpulse': 'MaximumPulse'}, inplace=True)

print(df)

import pandas as pd
import csv
df = pd.read_csv('data.csv')
df.to_csv('new_data.csv', index=False)

